### ISSUE TITLE
ability to login and logout

### ISSUE THREAD

**Issue by perarnedg** [heytrav/epp-reg#1]
Hi,

Is it possible to have an ability to logut and login while the service is running? I am able to logout (with an error on the function server.close() (line 47 lib/connections.js), but not able to login afterwards.

**Comment by heytrav** [comment]
Could you please explain what use case being able to arbitrarily `login` and `logout` would serve that starting and stopping the service doesn't already provide?

Please note that it is actually part of the intended design of [nodepp](https://github.com/heytrav/nodepp) that it logs into respective registries when started and only logs out when the app is stopped like it would be if being managed by supervisord or upstart or similar.  I did not really foresee any need for underlying client applications to log the service out of of the registry.  In my experience with EPP, there is generally very little need to arbitrarily login and logout. The commands themselves were mainly implemented for completeness of the protocol. 

The only reason I can think of would be that you want to use `<login>` to change the password (which you can also do with the `<poll>` command). I admit this could be an oversight on my part.

Sending the `<logout>` command to a running service ends the connection with the registry and causes the child worker process for that registry to exit. I presume this is the cause of that error you are seeing. The parent process may keep running, but there is nothing implemented at the moment for respawning connections. If you do indeed have a use case for this, I would be willing to implement that.

**Comment by perarnedg** [comment]
Hello,

The reasoning for being able to log in and out was to not having to stop and start the service. I will look into using supervisord or upstart for this. With my use I would only call the service when I need an action to happen towards the epp server, and I found it a bit illogical to having to start a webservice to do an action, rather then calling the action, which connects to the server, acts and then shuts down the connection automatically, instead of starting a service, calling an action, and then stopping the service again.

**Comment by heytrav** [comment]
>and then shut it down afterwards

What do you mean by this? Once the nodepp daemon is started and connects to a registry, it sends the `hello` command periodically to keep the connection open. It shouldn't shut down or need to be shut down respectively. This is to avoid the unneeded overhead of always creating the connection each time a client wants to send something.

**Comment by perarnedg** [comment]
Hi,

I'm sorry, but I did write the issue on the wrong project. I meant to write it in nodepp. Anyways, the reason I would like to issue a command and then logout is that the organisation running domain names that the EPP is communicating with is quite strict in how we access them. As far as I know, it is not permitted to have a constant link to them, and also the number of requests per 24 hours is limited.

**Comment by heytrav** [comment]
That is indeed a bit strict. 

Out of curiosity, which registry is that? I worked with a number of EPP registries before (Verisign, EURID, Afilias, Neustar, etc.) and none of them had issues with maintaining a constant connection that I was aware of. In fact, that is the purpose of the `<hello/>` command as far as I am aware.  Some registries would kill the connection periodically, but that was generally not a problem.

**Comment by heytrav** [comment]
I implemented login/logout as requested on the nodepp repo and checked it into npm.  If you have any problems with the way it works, please reopen an issue in the nodepp repository.
